"""Multi-activity contract for workplace practice: multiple-choice and
written-response scenarios, submissions and reflective feedback (AC 4.4.2,
4.5.1, 4.5.2)."""

from datetime import datetime, timezone

import pytest
from pydantic import ValidationError

from app.providers.scenario_provider import FeedbackContent, ScenarioContent
from app.repositories.interfaces.practice_session_repository import (
    PracticeScenario,
    ReflectiveFeedback,
    ScenarioAttempt,
    ScenarioOption,
)
from app.schemas.practice_session import PracticeScenarioResponse
from app.schemas.scenario_response import ScenarioResponseCreate

OPTION_A = {"option_id": "option_a", "text": "Approve it because it was generated by an AI tool"}
OPTION_B = {"option_id": "option_b", "text": "Review the logic, tests, security and error handling"}

MULTIPLE_CHOICE = {
    "scenario_id": "software_ai_code_review",
    "title": "Reviewing AI-generated code",
    "workplace_area": "Code review queue",
    "situation": "A teammate submits AI-generated API code for review.",
    "task": "What should you do before approving the change?",
    "activity_type": "multiple_choice",
    "options": [OPTION_A, OPTION_B],
    "guidance": [],
    "skills_used": ["Code review"],
    "new_skill_focus": "AI-assisted development",
}

WRITTEN = {
    **{key: value for key, value in MULTIPLE_CHOICE.items() if key != "options"},
    "task": "Write the review comment you would leave.",
    "activity_type": "written_response",
}

FEEDBACK = {
    "what_worked_well": ["Reviewing the tests first helps you trust the change."],
    "trade_offs": ["A thorough review takes longer, which can delay the release."],
    "areas_to_consider": ["How would you share what you found with the teammate?"],
    "skill_to_explore": {"skill": "AI-assisted development", "why_relevant": "Teams now review generated code."},
}


# --- Scenarios -------------------------------------------------------------


def test_multiple_choice_scenario_with_two_options_is_valid():
    content = ScenarioContent.model_validate(MULTIPLE_CHOICE)

    assert content.activity_type == "multiple_choice"
    assert [(option.option_id, option.text) for option in content.options] == [
        (OPTION_A["option_id"], OPTION_A["text"]),
        (OPTION_B["option_id"], OPTION_B["text"]),
    ]


def test_written_response_scenario_has_no_options():
    content = ScenarioContent.model_validate(WRITTEN)

    assert content.activity_type == "written_response"
    assert content.options == []


@pytest.mark.parametrize(
    "change",
    [
        {"options": []},
        {"options": [OPTION_A]},
        {"options": [OPTION_A, {**OPTION_B, "option_id": "option_a"}]},
        {"options": [OPTION_A, {**OPTION_B, "option_id": "Option B"}]},
        {"options": [OPTION_A, {**OPTION_B, "option_id": ""}]},
        {"options": [OPTION_A, {**OPTION_B, "option_id": "x" * 65}]},
        {"options": [OPTION_A, {**OPTION_B, "text": "   "}]},
        {"options": [OPTION_A, {**OPTION_B, "text": "x" * 301}]},
        {"options": [OPTION_A, {"option_id": "option_b"}]},
        {"options": [OPTION_A, {**OPTION_B, "is_correct": True}]},
        {"options": [{"option_id": f"option_{n}", "text": "An approach"} for n in range(7)]},
        {"correct_option_id": "option_b"},
        {"activity_type": "multiple_select"},
        {"activity_type": "drag_and_drop"},
    ],
)
def test_invalid_multiple_choice_scenario_is_rejected(change):
    with pytest.raises(ValidationError):
        ScenarioContent.model_validate({**MULTIPLE_CHOICE, **change})


def test_written_response_scenario_with_options_is_rejected():
    with pytest.raises(ValidationError):
        ScenarioContent.model_validate({**WRITTEN, "options": [OPTION_A, OPTION_B]})


def test_scenario_without_an_activity_type_is_rejected():
    without_type = {key: value for key, value in MULTIPLE_CHOICE.items() if key != "activity_type"}

    with pytest.raises(ValidationError):
        ScenarioContent.model_validate(without_type)


# --- Submissions -----------------------------------------------------------


def test_multiple_choice_submission_selects_one_option():
    submission = ScenarioResponseCreate.model_validate({"selected_option_id": "option_b"})

    assert submission.selected_option_id == "option_b"
    assert submission.response_text is None


def test_written_submission_sends_trimmed_text():
    submission = ScenarioResponseCreate.model_validate(
        {"response_text": "  I would begin by reviewing the tests and logs.  "}
    )

    assert submission.response_text == "I would begin by reviewing the tests and logs."
    assert submission.selected_option_id is None


@pytest.mark.parametrize(
    "body",
    [
        {},
        {"selected_option_id": None},
        {"response_text": None},
        {"selected_option_id": "option_b", "response_text": "I would review it."},
        {"selected_option_id": "option_b", "response_text": None},
        {"response_text": "I would review it.", "selected_option_id": None},
        {"selected_option_id": ""},
        {"selected_option_id": "Option B"},
        {"selected_option_id": "option_b; drop table"},
        {"selected_option_id": "x" * 65},
        {"selected_option_id": 2},
        {"selected_option_id": ["option_a", "option_b"]},
        {"selected_option_ids": ["option_b"]},
        {"selected_option_id": "option_b", "is_correct": True},
    ],
)
def test_invalid_submission_is_rejected(body):
    with pytest.raises(ValidationError):
        ScenarioResponseCreate.model_validate(body)


# --- Feedback --------------------------------------------------------------


def test_feedback_can_explain_trade_offs():
    feedback = FeedbackContent.model_validate(FEEDBACK)

    assert feedback.trade_offs == FEEDBACK["trade_offs"]


def test_trade_offs_are_optional_for_written_feedback():
    without_trade_offs = {key: value for key, value in FEEDBACK.items() if key != "trade_offs"}

    assert FeedbackContent.model_validate(without_trade_offs).trade_offs == []


@pytest.mark.parametrize(
    "change",
    [
        {"what_worked_well": ["That was the correct option."]},
        {"what_worked_well": ["Correct!"]},
        {"areas_to_consider": ["Option A was incorrect."]},
        {"trade_offs": ["The right answer was to review the tests."]},
        {"trade_offs": ["This was the wrong choice for a release."]},
        {"areas_to_consider": ["Your readiness score went up."]},
        {"areas_to_consider": ["This improves your employability."]},
        {"trade_offs": ["You scored 4 out of 5."]},
        {"trade_offs": ["x" * 501]},
        {"trade_offs": ["A trade-off."] * 6},
        {"is_correct": True},
        {"readiness": "high"},
    ],
)
def test_feedback_rejects_labels_scores_and_bad_shapes(change):
    with pytest.raises(ValidationError):
        FeedbackContent.model_validate({**FEEDBACK, **change})


def test_feedback_allows_ordinary_wording_near_the_blocked_labels():
    wording = "Checking the error handling works correctly first can slow the release slightly."

    feedback = FeedbackContent.model_validate({**FEEDBACK, "trade_offs": [wording]})

    assert feedback.trade_offs == [wording]


# --- API response shape ----------------------------------------------------


def test_answered_multiple_choice_scenario_serialises_options_and_selection():
    submitted_at = datetime(2026, 9, 14, 10, 6, tzinfo=timezone.utc)
    scenario = PracticeScenario(
        scenario_id="software_ai_code_review",
        title="Reviewing AI-generated code",
        workplace_area="Code review queue",
        situation="A teammate submits AI-generated API code for review.",
        task="What should you do before approving the change?",
        activity_type="multiple_choice",
        guidance=[],
        skills_used=["Code review"],
        new_skill_focus=None,
        options=[ScenarioOption(**OPTION_A), ScenarioOption(**OPTION_B)],
        status="completed",
        response=ScenarioAttempt(submitted_at=submitted_at, selected_option_id="option_b"),
        feedback=ReflectiveFeedback(
            what_worked_well=FEEDBACK["what_worked_well"],
            areas_to_consider=FEEDBACK["areas_to_consider"],
            trade_offs=FEEDBACK["trade_offs"],
        ),
        feedback_status="available",
    )

    body = PracticeScenarioResponse.model_validate(scenario).model_dump(mode="json")

    assert body["activity_type"] == "multiple_choice"
    assert body["options"] == [OPTION_A, OPTION_B]
    assert body["response"] == {
        "selected_option_id": "option_b",
        "response_text": None,
        "submitted_at": "2026-09-14T10:06:00Z",
    }
    assert body["feedback"]["trade_offs"] == FEEDBACK["trade_offs"]
    assert not any("correct" in key for option in body["options"] for key in option)
